// AUTO-GENERATED FILE (runtime)
// Generated by IpcRouter
import type { z } from 'zod'
import type * as Mod_auth from '@main/routes/auth'
import type * as Mod_macaddress from '@main/routes/macaddress'
import type * as Mod_notification from '@main/routes/notification'
import type * as Mod_query_departemen from '@main/routes/query/departemen'
import type * as Mod_query_diagnostic from '@main/routes/query/diagnostic'
import type * as Mod_query_doctorSchedule from '@main/routes/query/doctorSchedule'
import type * as Mod_query_encounter from '@main/routes/query/encounter'
import type * as Mod_query_expense from '@main/routes/query/expense'
import type * as Mod_query_expenseHead from '@main/routes/query/expenseHead'
import type * as Mod_query_export from '@main/routes/query/export'
import type * as Mod_query_hakAkses from '@main/routes/query/hakAkses'
import type * as Mod_query_jaminan from '@main/routes/query/jaminan'
import type * as Mod_query_kepegawaian from '@main/routes/query/kepegawaian'
import type * as Mod_query_medicalStaffSchedule from '@main/routes/query/medicalStaffSchedule'
import type * as Mod_query_medicationDispense from '@main/routes/query/medicationDispense'
import type * as Mod_query_medicationRequest from '@main/routes/query/medicationRequest'
import type * as Mod_query_medicine from '@main/routes/query/medicine'
import type * as Mod_query_medicineBrand from '@main/routes/query/medicineBrand'
import type * as Mod_query_medicineCategory from '@main/routes/query/medicineCategory'
import type * as Mod_query_patient from '@main/routes/query/patient'
import type * as Mod_query_pegawai from '@main/routes/query/pegawai'
import type * as Mod_query_poli from '@main/routes/query/poli'
import type * as Mod_query_productionFormula from '@main/routes/query/productionFormula'
import type * as Mod_query_rawMaterial from '@main/routes/query/rawMaterial'
import type * as Mod_query_rawMaterialCategory from '@main/routes/query/rawMaterialCategory'
import type * as Mod_query_serviceRequest from '@main/routes/query/serviceRequest'
import type * as Mod_query_suplier from '@main/routes/query/suplier'
import type * as Mod_user from '@main/routes/user'
type Invoke<Args = unknown, Result = unknown> = (args?: Args) => Promise<Result>
type InferArgs<M, K extends string> = M extends { schemas: Record<string, any> }
  ? K extends keyof M['schemas']
    ? M['schemas'][K] extends { args: infer A extends z.ZodTypeAny }
      ? z.input<A>
      : unknown
    : unknown
  : M extends { schemas: infer S }
  ? K extends keyof S
    ? S[K] extends { args: infer A extends z.ZodTypeAny }
      ? z.input<A>
      : unknown
    : unknown
  : M extends { argsSchema: infer A extends z.ZodTypeAny }
  ? z.input<A>
  : unknown
type InferResult<M, K extends string> = M extends { schemas: Record<string, any> }
  ? K extends keyof M['schemas']
    ? M['schemas'][K] extends { result: infer R extends z.ZodTypeAny }
      ? z.output<R>
      : unknown
    : unknown
  : M extends { schemas: infer S }
  ? K extends keyof S
    ? S[K] extends { result: infer R extends z.ZodTypeAny }
      ? z.output<R>
      : unknown
    : unknown
  : M extends { resultSchema: infer R extends z.ZodTypeAny }
  ? z.output<R>
  : unknown
type Args_Mod_auth_getSession = InferArgs<typeof Mod_auth, 'getSession'>
type Result_Mod_auth_getSession = InferResult<typeof Mod_auth, 'getSession'>
type Args_Mod_auth_login = InferArgs<typeof Mod_auth, 'login'>
type Result_Mod_auth_login = InferResult<typeof Mod_auth, 'login'>
type Args_Mod_auth_logout = InferArgs<typeof Mod_auth, 'logout'>
type Result_Mod_auth_logout = InferResult<typeof Mod_auth, 'logout'>
type Args_Mod_auth_status = InferArgs<typeof Mod_auth, 'status'>
type Result_Mod_auth_status = InferResult<typeof Mod_auth, 'status'>
type Args_Mod_macaddress_getPrimaryMacAddress = InferArgs<typeof Mod_macaddress, 'getPrimaryMacAddress'>
type Result_Mod_macaddress_getPrimaryMacAddress = InferResult<typeof Mod_macaddress, 'getPrimaryMacAddress'>
type Args_Mod_notification_send = InferArgs<typeof Mod_notification, 'send'>
type Result_Mod_notification_send = InferResult<typeof Mod_notification, 'send'>
type Args_Mod_query_departemen_list = InferArgs<typeof Mod_query_departemen, 'list'>
type Result_Mod_query_departemen_list = InferResult<typeof Mod_query_departemen, 'list'>
type Args_Mod_query_diagnostic_create = InferArgs<typeof Mod_query_diagnostic, 'create'>
type Result_Mod_query_diagnostic_create = InferResult<typeof Mod_query_diagnostic, 'create'>
type Args_Mod_query_diagnostic_deleteById = InferArgs<typeof Mod_query_diagnostic, 'deleteById'>
type Result_Mod_query_diagnostic_deleteById = InferResult<typeof Mod_query_diagnostic, 'deleteById'>
type Args_Mod_query_diagnostic_getById = InferArgs<typeof Mod_query_diagnostic, 'getById'>
type Result_Mod_query_diagnostic_getById = InferResult<typeof Mod_query_diagnostic, 'getById'>
type Args_Mod_query_diagnostic_list = InferArgs<typeof Mod_query_diagnostic, 'list'>
type Result_Mod_query_diagnostic_list = InferResult<typeof Mod_query_diagnostic, 'list'>
type Args_Mod_query_diagnostic_update = InferArgs<typeof Mod_query_diagnostic, 'update'>
type Result_Mod_query_diagnostic_update = InferResult<typeof Mod_query_diagnostic, 'update'>
type Args_Mod_query_doctorSchedule_create = InferArgs<typeof Mod_query_doctorSchedule, 'create'>
type Result_Mod_query_doctorSchedule_create = InferResult<typeof Mod_query_doctorSchedule, 'create'>
type Args_Mod_query_doctorSchedule_deleteById = InferArgs<typeof Mod_query_doctorSchedule, 'deleteById'>
type Result_Mod_query_doctorSchedule_deleteById = InferResult<typeof Mod_query_doctorSchedule, 'deleteById'>
type Args_Mod_query_doctorSchedule_getById = InferArgs<typeof Mod_query_doctorSchedule, 'getById'>
type Result_Mod_query_doctorSchedule_getById = InferResult<typeof Mod_query_doctorSchedule, 'getById'>
type Args_Mod_query_doctorSchedule_list = InferArgs<typeof Mod_query_doctorSchedule, 'list'>
type Result_Mod_query_doctorSchedule_list = InferResult<typeof Mod_query_doctorSchedule, 'list'>
type Args_Mod_query_doctorSchedule_update = InferArgs<typeof Mod_query_doctorSchedule, 'update'>
type Result_Mod_query_doctorSchedule_update = InferResult<typeof Mod_query_doctorSchedule, 'update'>
type Args_Mod_query_encounter_create = InferArgs<typeof Mod_query_encounter, 'create'>
type Result_Mod_query_encounter_create = InferResult<typeof Mod_query_encounter, 'create'>
type Args_Mod_query_encounter_deleteById = InferArgs<typeof Mod_query_encounter, 'deleteById'>
type Result_Mod_query_encounter_deleteById = InferResult<typeof Mod_query_encounter, 'deleteById'>
type Args_Mod_query_encounter_getById = InferArgs<typeof Mod_query_encounter, 'getById'>
type Result_Mod_query_encounter_getById = InferResult<typeof Mod_query_encounter, 'getById'>
type Args_Mod_query_encounter_list = InferArgs<typeof Mod_query_encounter, 'list'>
type Result_Mod_query_encounter_list = InferResult<typeof Mod_query_encounter, 'list'>
type Args_Mod_query_encounter_update = InferArgs<typeof Mod_query_encounter, 'update'>
type Result_Mod_query_encounter_update = InferResult<typeof Mod_query_encounter, 'update'>
type Args_Mod_query_expense_create = InferArgs<typeof Mod_query_expense, 'create'>
type Result_Mod_query_expense_create = InferResult<typeof Mod_query_expense, 'create'>
type Args_Mod_query_expense_deleteById = InferArgs<typeof Mod_query_expense, 'deleteById'>
type Result_Mod_query_expense_deleteById = InferResult<typeof Mod_query_expense, 'deleteById'>
type Args_Mod_query_expense_list = InferArgs<typeof Mod_query_expense, 'list'>
type Result_Mod_query_expense_list = InferResult<typeof Mod_query_expense, 'list'>
type Args_Mod_query_expense_seed = InferArgs<typeof Mod_query_expense, 'seed'>
type Result_Mod_query_expense_seed = InferResult<typeof Mod_query_expense, 'seed'>
type Args_Mod_query_expense_update = InferArgs<typeof Mod_query_expense, 'update'>
type Result_Mod_query_expense_update = InferResult<typeof Mod_query_expense, 'update'>
type Args_Mod_query_expenseHead_list = InferArgs<typeof Mod_query_expenseHead, 'list'>
type Result_Mod_query_expenseHead_list = InferResult<typeof Mod_query_expenseHead, 'list'>
type Args_Mod_query_expenseHead_seed = InferArgs<typeof Mod_query_expenseHead, 'seed'>
type Result_Mod_query_expenseHead_seed = InferResult<typeof Mod_query_expenseHead, 'seed'>
type Args_Mod_query_export_exportCsv = InferArgs<typeof Mod_query_export, 'exportCsv'>
type Result_Mod_query_export_exportCsv = InferResult<typeof Mod_query_export, 'exportCsv'>
type Args_Mod_query_hakAkses_getByCode = InferArgs<typeof Mod_query_hakAkses, 'getByCode'>
type Result_Mod_query_hakAkses_getByCode = InferResult<typeof Mod_query_hakAkses, 'getByCode'>
type Args_Mod_query_jaminan_create = InferArgs<typeof Mod_query_jaminan, 'create'>
type Result_Mod_query_jaminan_create = InferResult<typeof Mod_query_jaminan, 'create'>
type Args_Mod_query_jaminan_deleteById = InferArgs<typeof Mod_query_jaminan, 'deleteById'>
type Result_Mod_query_jaminan_deleteById = InferResult<typeof Mod_query_jaminan, 'deleteById'>
type Args_Mod_query_jaminan_getById = InferArgs<typeof Mod_query_jaminan, 'getById'>
type Result_Mod_query_jaminan_getById = InferResult<typeof Mod_query_jaminan, 'getById'>
type Args_Mod_query_jaminan_list = InferArgs<typeof Mod_query_jaminan, 'list'>
type Result_Mod_query_jaminan_list = InferResult<typeof Mod_query_jaminan, 'list'>
type Args_Mod_query_jaminan_update = InferArgs<typeof Mod_query_jaminan, 'update'>
type Result_Mod_query_jaminan_update = InferResult<typeof Mod_query_jaminan, 'update'>
type Args_Mod_query_kepegawaian_create = InferArgs<typeof Mod_query_kepegawaian, 'create'>
type Result_Mod_query_kepegawaian_create = InferResult<typeof Mod_query_kepegawaian, 'create'>
type Args_Mod_query_kepegawaian_deleteById = InferArgs<typeof Mod_query_kepegawaian, 'deleteById'>
type Result_Mod_query_kepegawaian_deleteById = InferResult<typeof Mod_query_kepegawaian, 'deleteById'>
type Args_Mod_query_kepegawaian_getById = InferArgs<typeof Mod_query_kepegawaian, 'getById'>
type Result_Mod_query_kepegawaian_getById = InferResult<typeof Mod_query_kepegawaian, 'getById'>
type Args_Mod_query_kepegawaian_list = InferArgs<typeof Mod_query_kepegawaian, 'list'>
type Result_Mod_query_kepegawaian_list = InferResult<typeof Mod_query_kepegawaian, 'list'>
type Args_Mod_query_kepegawaian_update = InferArgs<typeof Mod_query_kepegawaian, 'update'>
type Result_Mod_query_kepegawaian_update = InferResult<typeof Mod_query_kepegawaian, 'update'>
type Args_Mod_query_medicalStaffSchedule_create = InferArgs<typeof Mod_query_medicalStaffSchedule, 'create'>
type Result_Mod_query_medicalStaffSchedule_create = InferResult<typeof Mod_query_medicalStaffSchedule, 'create'>
type Args_Mod_query_medicalStaffSchedule_deleteById = InferArgs<typeof Mod_query_medicalStaffSchedule, 'deleteById'>
type Result_Mod_query_medicalStaffSchedule_deleteById = InferResult<typeof Mod_query_medicalStaffSchedule, 'deleteById'>
type Args_Mod_query_medicalStaffSchedule_getById = InferArgs<typeof Mod_query_medicalStaffSchedule, 'getById'>
type Result_Mod_query_medicalStaffSchedule_getById = InferResult<typeof Mod_query_medicalStaffSchedule, 'getById'>
type Args_Mod_query_medicalStaffSchedule_list = InferArgs<typeof Mod_query_medicalStaffSchedule, 'list'>
type Result_Mod_query_medicalStaffSchedule_list = InferResult<typeof Mod_query_medicalStaffSchedule, 'list'>
type Args_Mod_query_medicalStaffSchedule_update = InferArgs<typeof Mod_query_medicalStaffSchedule, 'update'>
type Result_Mod_query_medicalStaffSchedule_update = InferResult<typeof Mod_query_medicalStaffSchedule, 'update'>
type Args_Mod_query_medicationDispense_createFromRequest = InferArgs<typeof Mod_query_medicationDispense, 'createFromRequest'>
type Result_Mod_query_medicationDispense_createFromRequest = InferResult<typeof Mod_query_medicationDispense, 'createFromRequest'>
type Args_Mod_query_medicationDispense_list = InferArgs<typeof Mod_query_medicationDispense, 'list'>
type Result_Mod_query_medicationDispense_list = InferResult<typeof Mod_query_medicationDispense, 'list'>
type Args_Mod_query_medicationDispense_update = InferArgs<typeof Mod_query_medicationDispense, 'update'>
type Result_Mod_query_medicationDispense_update = InferResult<typeof Mod_query_medicationDispense, 'update'>
type Args_Mod_query_medicationRequest_create = InferArgs<typeof Mod_query_medicationRequest, 'create'>
type Result_Mod_query_medicationRequest_create = InferResult<typeof Mod_query_medicationRequest, 'create'>
type Args_Mod_query_medicationRequest_deleteById = InferArgs<typeof Mod_query_medicationRequest, 'deleteById'>
type Result_Mod_query_medicationRequest_deleteById = InferResult<typeof Mod_query_medicationRequest, 'deleteById'>
type Args_Mod_query_medicationRequest_getById = InferArgs<typeof Mod_query_medicationRequest, 'getById'>
type Result_Mod_query_medicationRequest_getById = InferResult<typeof Mod_query_medicationRequest, 'getById'>
type Args_Mod_query_medicationRequest_list = InferArgs<typeof Mod_query_medicationRequest, 'list'>
type Result_Mod_query_medicationRequest_list = InferResult<typeof Mod_query_medicationRequest, 'list'>
type Args_Mod_query_medicationRequest_update = InferArgs<typeof Mod_query_medicationRequest, 'update'>
type Result_Mod_query_medicationRequest_update = InferResult<typeof Mod_query_medicationRequest, 'update'>
type Args_Mod_query_medicine_create = InferArgs<typeof Mod_query_medicine, 'create'>
type Result_Mod_query_medicine_create = InferResult<typeof Mod_query_medicine, 'create'>
type Args_Mod_query_medicine_deleteById = InferArgs<typeof Mod_query_medicine, 'deleteById'>
type Result_Mod_query_medicine_deleteById = InferResult<typeof Mod_query_medicine, 'deleteById'>
type Args_Mod_query_medicine_getById = InferArgs<typeof Mod_query_medicine, 'getById'>
type Result_Mod_query_medicine_getById = InferResult<typeof Mod_query_medicine, 'getById'>
type Args_Mod_query_medicine_list = InferArgs<typeof Mod_query_medicine, 'list'>
type Result_Mod_query_medicine_list = InferResult<typeof Mod_query_medicine, 'list'>
type Args_Mod_query_medicine_update = InferArgs<typeof Mod_query_medicine, 'update'>
type Result_Mod_query_medicine_update = InferResult<typeof Mod_query_medicine, 'update'>
type Args_Mod_query_medicineBrand_create = InferArgs<typeof Mod_query_medicineBrand, 'create'>
type Result_Mod_query_medicineBrand_create = InferResult<typeof Mod_query_medicineBrand, 'create'>
type Args_Mod_query_medicineBrand_deleteById = InferArgs<typeof Mod_query_medicineBrand, 'deleteById'>
type Result_Mod_query_medicineBrand_deleteById = InferResult<typeof Mod_query_medicineBrand, 'deleteById'>
type Args_Mod_query_medicineBrand_getById = InferArgs<typeof Mod_query_medicineBrand, 'getById'>
type Result_Mod_query_medicineBrand_getById = InferResult<typeof Mod_query_medicineBrand, 'getById'>
type Args_Mod_query_medicineBrand_list = InferArgs<typeof Mod_query_medicineBrand, 'list'>
type Result_Mod_query_medicineBrand_list = InferResult<typeof Mod_query_medicineBrand, 'list'>
type Args_Mod_query_medicineBrand_update = InferArgs<typeof Mod_query_medicineBrand, 'update'>
type Result_Mod_query_medicineBrand_update = InferResult<typeof Mod_query_medicineBrand, 'update'>
type Args_Mod_query_medicineCategory_create = InferArgs<typeof Mod_query_medicineCategory, 'create'>
type Result_Mod_query_medicineCategory_create = InferResult<typeof Mod_query_medicineCategory, 'create'>
type Args_Mod_query_medicineCategory_deleteById = InferArgs<typeof Mod_query_medicineCategory, 'deleteById'>
type Result_Mod_query_medicineCategory_deleteById = InferResult<typeof Mod_query_medicineCategory, 'deleteById'>
type Args_Mod_query_medicineCategory_getById = InferArgs<typeof Mod_query_medicineCategory, 'getById'>
type Result_Mod_query_medicineCategory_getById = InferResult<typeof Mod_query_medicineCategory, 'getById'>
type Args_Mod_query_medicineCategory_list = InferArgs<typeof Mod_query_medicineCategory, 'list'>
type Result_Mod_query_medicineCategory_list = InferResult<typeof Mod_query_medicineCategory, 'list'>
type Args_Mod_query_medicineCategory_update = InferArgs<typeof Mod_query_medicineCategory, 'update'>
type Result_Mod_query_medicineCategory_update = InferResult<typeof Mod_query_medicineCategory, 'update'>
type Args_Mod_query_patient_create = InferArgs<typeof Mod_query_patient, 'create'>
type Result_Mod_query_patient_create = InferResult<typeof Mod_query_patient, 'create'>
type Args_Mod_query_patient_deleteById = InferArgs<typeof Mod_query_patient, 'deleteById'>
type Result_Mod_query_patient_deleteById = InferResult<typeof Mod_query_patient, 'deleteById'>
type Args_Mod_query_patient_getById = InferArgs<typeof Mod_query_patient, 'getById'>
type Result_Mod_query_patient_getById = InferResult<typeof Mod_query_patient, 'getById'>
type Args_Mod_query_patient_list = InferArgs<typeof Mod_query_patient, 'list'>
type Result_Mod_query_patient_list = InferResult<typeof Mod_query_patient, 'list'>
type Args_Mod_query_patient_update = InferArgs<typeof Mod_query_patient, 'update'>
type Result_Mod_query_patient_update = InferResult<typeof Mod_query_patient, 'update'>
type Args_Mod_query_pegawai_create = InferArgs<typeof Mod_query_pegawai, 'create'>
type Result_Mod_query_pegawai_create = InferResult<typeof Mod_query_pegawai, 'create'>
type Args_Mod_query_pegawai_deleteById = InferArgs<typeof Mod_query_pegawai, 'deleteById'>
type Result_Mod_query_pegawai_deleteById = InferResult<typeof Mod_query_pegawai, 'deleteById'>
type Args_Mod_query_pegawai_getById = InferArgs<typeof Mod_query_pegawai, 'getById'>
type Result_Mod_query_pegawai_getById = InferResult<typeof Mod_query_pegawai, 'getById'>
type Args_Mod_query_pegawai_list = InferArgs<typeof Mod_query_pegawai, 'list'>
type Result_Mod_query_pegawai_list = InferResult<typeof Mod_query_pegawai, 'list'>
type Args_Mod_query_pegawai_update = InferArgs<typeof Mod_query_pegawai, 'update'>
type Result_Mod_query_pegawai_update = InferResult<typeof Mod_query_pegawai, 'update'>
type Args_Mod_query_poli_list = InferArgs<typeof Mod_query_poli, 'list'>
type Result_Mod_query_poli_list = InferResult<typeof Mod_query_poli, 'list'>
type Args_Mod_query_productionFormula_create = InferArgs<typeof Mod_query_productionFormula, 'create'>
type Result_Mod_query_productionFormula_create = InferResult<typeof Mod_query_productionFormula, 'create'>
type Args_Mod_query_productionFormula_deleteById = InferArgs<typeof Mod_query_productionFormula, 'deleteById'>
type Result_Mod_query_productionFormula_deleteById = InferResult<typeof Mod_query_productionFormula, 'deleteById'>
type Args_Mod_query_productionFormula_getById = InferArgs<typeof Mod_query_productionFormula, 'getById'>
type Result_Mod_query_productionFormula_getById = InferResult<typeof Mod_query_productionFormula, 'getById'>
type Args_Mod_query_productionFormula_list = InferArgs<typeof Mod_query_productionFormula, 'list'>
type Result_Mod_query_productionFormula_list = InferResult<typeof Mod_query_productionFormula, 'list'>
type Args_Mod_query_productionFormula_update = InferArgs<typeof Mod_query_productionFormula, 'update'>
type Result_Mod_query_productionFormula_update = InferResult<typeof Mod_query_productionFormula, 'update'>
type Args_Mod_query_rawMaterial_create = InferArgs<typeof Mod_query_rawMaterial, 'create'>
type Result_Mod_query_rawMaterial_create = InferResult<typeof Mod_query_rawMaterial, 'create'>
type Args_Mod_query_rawMaterial_deleteById = InferArgs<typeof Mod_query_rawMaterial, 'deleteById'>
type Result_Mod_query_rawMaterial_deleteById = InferResult<typeof Mod_query_rawMaterial, 'deleteById'>
type Args_Mod_query_rawMaterial_list = InferArgs<typeof Mod_query_rawMaterial, 'list'>
type Result_Mod_query_rawMaterial_list = InferResult<typeof Mod_query_rawMaterial, 'list'>
type Args_Mod_query_rawMaterial_read = InferArgs<typeof Mod_query_rawMaterial, 'read'>
type Result_Mod_query_rawMaterial_read = InferResult<typeof Mod_query_rawMaterial, 'read'>
type Args_Mod_query_rawMaterial_update = InferArgs<typeof Mod_query_rawMaterial, 'update'>
type Result_Mod_query_rawMaterial_update = InferResult<typeof Mod_query_rawMaterial, 'update'>
type Args_Mod_query_rawMaterialCategory_create = InferArgs<typeof Mod_query_rawMaterialCategory, 'create'>
type Result_Mod_query_rawMaterialCategory_create = InferResult<typeof Mod_query_rawMaterialCategory, 'create'>
type Args_Mod_query_rawMaterialCategory_deleteById = InferArgs<typeof Mod_query_rawMaterialCategory, 'deleteById'>
type Result_Mod_query_rawMaterialCategory_deleteById = InferResult<typeof Mod_query_rawMaterialCategory, 'deleteById'>
type Args_Mod_query_rawMaterialCategory_getById = InferArgs<typeof Mod_query_rawMaterialCategory, 'getById'>
type Result_Mod_query_rawMaterialCategory_getById = InferResult<typeof Mod_query_rawMaterialCategory, 'getById'>
type Args_Mod_query_rawMaterialCategory_list = InferArgs<typeof Mod_query_rawMaterialCategory, 'list'>
type Result_Mod_query_rawMaterialCategory_list = InferResult<typeof Mod_query_rawMaterialCategory, 'list'>
type Args_Mod_query_rawMaterialCategory_update = InferArgs<typeof Mod_query_rawMaterialCategory, 'update'>
type Result_Mod_query_rawMaterialCategory_update = InferResult<typeof Mod_query_rawMaterialCategory, 'update'>
type Args_Mod_query_serviceRequest_create = InferArgs<typeof Mod_query_serviceRequest, 'create'>
type Result_Mod_query_serviceRequest_create = InferResult<typeof Mod_query_serviceRequest, 'create'>
type Args_Mod_query_serviceRequest_deleteById = InferArgs<typeof Mod_query_serviceRequest, 'deleteById'>
type Result_Mod_query_serviceRequest_deleteById = InferResult<typeof Mod_query_serviceRequest, 'deleteById'>
type Args_Mod_query_serviceRequest_exportCsv = InferArgs<typeof Mod_query_serviceRequest, 'exportCsv'>
type Result_Mod_query_serviceRequest_exportCsv = InferResult<typeof Mod_query_serviceRequest, 'exportCsv'>
type Args_Mod_query_serviceRequest_getById = InferArgs<typeof Mod_query_serviceRequest, 'getById'>
type Result_Mod_query_serviceRequest_getById = InferResult<typeof Mod_query_serviceRequest, 'getById'>
type Args_Mod_query_serviceRequest_list = InferArgs<typeof Mod_query_serviceRequest, 'list'>
type Result_Mod_query_serviceRequest_list = InferResult<typeof Mod_query_serviceRequest, 'list'>
type Args_Mod_query_serviceRequest_update = InferArgs<typeof Mod_query_serviceRequest, 'update'>
type Result_Mod_query_serviceRequest_update = InferResult<typeof Mod_query_serviceRequest, 'update'>
type Args_Mod_query_suplier_create = InferArgs<typeof Mod_query_suplier, 'create'>
type Result_Mod_query_suplier_create = InferResult<typeof Mod_query_suplier, 'create'>
type Args_Mod_query_suplier_list = InferArgs<typeof Mod_query_suplier, 'list'>
type Result_Mod_query_suplier_list = InferResult<typeof Mod_query_suplier, 'list'>
type Args_Mod_query_suplier_read = InferArgs<typeof Mod_query_suplier, 'read'>
type Result_Mod_query_suplier_read = InferResult<typeof Mod_query_suplier, 'read'>
type Args_Mod_query_suplier_remove = InferArgs<typeof Mod_query_suplier, 'remove'>
type Result_Mod_query_suplier_remove = InferResult<typeof Mod_query_suplier, 'remove'>
type Args_Mod_query_suplier_update = InferArgs<typeof Mod_query_suplier, 'update'>
type Result_Mod_query_suplier_update = InferResult<typeof Mod_query_suplier, 'update'>
type Args_Mod_user_create = InferArgs<typeof Mod_user, 'create'>
type Result_Mod_user_create = InferResult<typeof Mod_user, 'create'>
type Args_Mod_user_get = InferArgs<typeof Mod_user, 'get'>
type Result_Mod_user_get = InferResult<typeof Mod_user, 'get'>
type Args_Mod_user_list = InferArgs<typeof Mod_user, 'list'>
type Result_Mod_user_list = InferResult<typeof Mod_user, 'list'>
declare global {
  interface Window {
    api: {
      auth: {
        getSession: Invoke<Args_Mod_auth_getSession, Result_Mod_auth_getSession>
        login: Invoke<Args_Mod_auth_login, Result_Mod_auth_login>
        logout: Invoke<Args_Mod_auth_logout, Result_Mod_auth_logout>
        status: Invoke<Args_Mod_auth_status, Result_Mod_auth_status>
      }
      macaddress: {
        getPrimaryMacAddress: Invoke<Args_Mod_macaddress_getPrimaryMacAddress, Result_Mod_macaddress_getPrimaryMacAddress>
      }
      notification: {
        send: Invoke<Args_Mod_notification_send, Result_Mod_notification_send>
      }
      query: {
        departemen: {
          list: Invoke<Args_Mod_query_departemen_list, Result_Mod_query_departemen_list>
        }
        diagnostic: {
          create: Invoke<Args_Mod_query_diagnostic_create, Result_Mod_query_diagnostic_create>
          deleteById: Invoke<Args_Mod_query_diagnostic_deleteById, Result_Mod_query_diagnostic_deleteById>
          getById: Invoke<Args_Mod_query_diagnostic_getById, Result_Mod_query_diagnostic_getById>
          list: Invoke<Args_Mod_query_diagnostic_list, Result_Mod_query_diagnostic_list>
          update: Invoke<Args_Mod_query_diagnostic_update, Result_Mod_query_diagnostic_update>
        }
        doctorSchedule: {
          create: Invoke<Args_Mod_query_doctorSchedule_create, Result_Mod_query_doctorSchedule_create>
          deleteById: Invoke<Args_Mod_query_doctorSchedule_deleteById, Result_Mod_query_doctorSchedule_deleteById>
          getById: Invoke<Args_Mod_query_doctorSchedule_getById, Result_Mod_query_doctorSchedule_getById>
          list: Invoke<Args_Mod_query_doctorSchedule_list, Result_Mod_query_doctorSchedule_list>
          update: Invoke<Args_Mod_query_doctorSchedule_update, Result_Mod_query_doctorSchedule_update>
        }
        encounter: {
          create: Invoke<Args_Mod_query_encounter_create, Result_Mod_query_encounter_create>
          deleteById: Invoke<Args_Mod_query_encounter_deleteById, Result_Mod_query_encounter_deleteById>
          getById: Invoke<Args_Mod_query_encounter_getById, Result_Mod_query_encounter_getById>
          list: Invoke<Args_Mod_query_encounter_list, Result_Mod_query_encounter_list>
          update: Invoke<Args_Mod_query_encounter_update, Result_Mod_query_encounter_update>
        }
        expense: {
          create: Invoke<Args_Mod_query_expense_create, Result_Mod_query_expense_create>
          deleteById: Invoke<Args_Mod_query_expense_deleteById, Result_Mod_query_expense_deleteById>
          list: Invoke<Args_Mod_query_expense_list, Result_Mod_query_expense_list>
          seed: Invoke<Args_Mod_query_expense_seed, Result_Mod_query_expense_seed>
          update: Invoke<Args_Mod_query_expense_update, Result_Mod_query_expense_update>
        }
        expenseHead: {
          list: Invoke<Args_Mod_query_expenseHead_list, Result_Mod_query_expenseHead_list>
          seed: Invoke<Args_Mod_query_expenseHead_seed, Result_Mod_query_expenseHead_seed>
        }
        export: {
          exportCsv: Invoke<Args_Mod_query_export_exportCsv, Result_Mod_query_export_exportCsv>
        }
        hakAkses: {
          getByCode: Invoke<Args_Mod_query_hakAkses_getByCode, Result_Mod_query_hakAkses_getByCode>
        }
        jaminan: {
          create: Invoke<Args_Mod_query_jaminan_create, Result_Mod_query_jaminan_create>
          deleteById: Invoke<Args_Mod_query_jaminan_deleteById, Result_Mod_query_jaminan_deleteById>
          getById: Invoke<Args_Mod_query_jaminan_getById, Result_Mod_query_jaminan_getById>
          list: Invoke<Args_Mod_query_jaminan_list, Result_Mod_query_jaminan_list>
          update: Invoke<Args_Mod_query_jaminan_update, Result_Mod_query_jaminan_update>
        }
        kepegawaian: {
          create: Invoke<Args_Mod_query_kepegawaian_create, Result_Mod_query_kepegawaian_create>
          deleteById: Invoke<Args_Mod_query_kepegawaian_deleteById, Result_Mod_query_kepegawaian_deleteById>
          getById: Invoke<Args_Mod_query_kepegawaian_getById, Result_Mod_query_kepegawaian_getById>
          list: Invoke<Args_Mod_query_kepegawaian_list, Result_Mod_query_kepegawaian_list>
          update: Invoke<Args_Mod_query_kepegawaian_update, Result_Mod_query_kepegawaian_update>
        }
        medicalStaffSchedule: {
          create: Invoke<Args_Mod_query_medicalStaffSchedule_create, Result_Mod_query_medicalStaffSchedule_create>
          deleteById: Invoke<Args_Mod_query_medicalStaffSchedule_deleteById, Result_Mod_query_medicalStaffSchedule_deleteById>
          getById: Invoke<Args_Mod_query_medicalStaffSchedule_getById, Result_Mod_query_medicalStaffSchedule_getById>
          list: Invoke<Args_Mod_query_medicalStaffSchedule_list, Result_Mod_query_medicalStaffSchedule_list>
          update: Invoke<Args_Mod_query_medicalStaffSchedule_update, Result_Mod_query_medicalStaffSchedule_update>
        }
        medicationDispense: {
          createFromRequest: Invoke<Args_Mod_query_medicationDispense_createFromRequest, Result_Mod_query_medicationDispense_createFromRequest>
          list: Invoke<Args_Mod_query_medicationDispense_list, Result_Mod_query_medicationDispense_list>
          update: Invoke<Args_Mod_query_medicationDispense_update, Result_Mod_query_medicationDispense_update>
        }
        medicationRequest: {
          create: Invoke<Args_Mod_query_medicationRequest_create, Result_Mod_query_medicationRequest_create>
          deleteById: Invoke<Args_Mod_query_medicationRequest_deleteById, Result_Mod_query_medicationRequest_deleteById>
          getById: Invoke<Args_Mod_query_medicationRequest_getById, Result_Mod_query_medicationRequest_getById>
          list: Invoke<Args_Mod_query_medicationRequest_list, Result_Mod_query_medicationRequest_list>
          update: Invoke<Args_Mod_query_medicationRequest_update, Result_Mod_query_medicationRequest_update>
        }
        medicine: {
          create: Invoke<Args_Mod_query_medicine_create, Result_Mod_query_medicine_create>
          deleteById: Invoke<Args_Mod_query_medicine_deleteById, Result_Mod_query_medicine_deleteById>
          getById: Invoke<Args_Mod_query_medicine_getById, Result_Mod_query_medicine_getById>
          list: Invoke<Args_Mod_query_medicine_list, Result_Mod_query_medicine_list>
          update: Invoke<Args_Mod_query_medicine_update, Result_Mod_query_medicine_update>
        }
        medicineBrand: {
          create: Invoke<Args_Mod_query_medicineBrand_create, Result_Mod_query_medicineBrand_create>
          deleteById: Invoke<Args_Mod_query_medicineBrand_deleteById, Result_Mod_query_medicineBrand_deleteById>
          getById: Invoke<Args_Mod_query_medicineBrand_getById, Result_Mod_query_medicineBrand_getById>
          list: Invoke<Args_Mod_query_medicineBrand_list, Result_Mod_query_medicineBrand_list>
          update: Invoke<Args_Mod_query_medicineBrand_update, Result_Mod_query_medicineBrand_update>
        }
        medicineCategory: {
          create: Invoke<Args_Mod_query_medicineCategory_create, Result_Mod_query_medicineCategory_create>
          deleteById: Invoke<Args_Mod_query_medicineCategory_deleteById, Result_Mod_query_medicineCategory_deleteById>
          getById: Invoke<Args_Mod_query_medicineCategory_getById, Result_Mod_query_medicineCategory_getById>
          list: Invoke<Args_Mod_query_medicineCategory_list, Result_Mod_query_medicineCategory_list>
          update: Invoke<Args_Mod_query_medicineCategory_update, Result_Mod_query_medicineCategory_update>
        }
        patient: {
          create: Invoke<Args_Mod_query_patient_create, Result_Mod_query_patient_create>
          deleteById: Invoke<Args_Mod_query_patient_deleteById, Result_Mod_query_patient_deleteById>
          getById: Invoke<Args_Mod_query_patient_getById, Result_Mod_query_patient_getById>
          list: Invoke<Args_Mod_query_patient_list, Result_Mod_query_patient_list>
          update: Invoke<Args_Mod_query_patient_update, Result_Mod_query_patient_update>
        }
        pegawai: {
          create: Invoke<Args_Mod_query_pegawai_create, Result_Mod_query_pegawai_create>
          deleteById: Invoke<Args_Mod_query_pegawai_deleteById, Result_Mod_query_pegawai_deleteById>
          getById: Invoke<Args_Mod_query_pegawai_getById, Result_Mod_query_pegawai_getById>
          list: Invoke<Args_Mod_query_pegawai_list, Result_Mod_query_pegawai_list>
          update: Invoke<Args_Mod_query_pegawai_update, Result_Mod_query_pegawai_update>
        }
        poli: {
          list: Invoke<Args_Mod_query_poli_list, Result_Mod_query_poli_list>
        }
        productionFormula: {
          create: Invoke<Args_Mod_query_productionFormula_create, Result_Mod_query_productionFormula_create>
          deleteById: Invoke<Args_Mod_query_productionFormula_deleteById, Result_Mod_query_productionFormula_deleteById>
          getById: Invoke<Args_Mod_query_productionFormula_getById, Result_Mod_query_productionFormula_getById>
          list: Invoke<Args_Mod_query_productionFormula_list, Result_Mod_query_productionFormula_list>
          update: Invoke<Args_Mod_query_productionFormula_update, Result_Mod_query_productionFormula_update>
        }
        rawMaterial: {
          create: Invoke<Args_Mod_query_rawMaterial_create, Result_Mod_query_rawMaterial_create>
          deleteById: Invoke<Args_Mod_query_rawMaterial_deleteById, Result_Mod_query_rawMaterial_deleteById>
          list: Invoke<Args_Mod_query_rawMaterial_list, Result_Mod_query_rawMaterial_list>
          read: Invoke<Args_Mod_query_rawMaterial_read, Result_Mod_query_rawMaterial_read>
          update: Invoke<Args_Mod_query_rawMaterial_update, Result_Mod_query_rawMaterial_update>
        }
        rawMaterialCategory: {
          create: Invoke<Args_Mod_query_rawMaterialCategory_create, Result_Mod_query_rawMaterialCategory_create>
          deleteById: Invoke<Args_Mod_query_rawMaterialCategory_deleteById, Result_Mod_query_rawMaterialCategory_deleteById>
          getById: Invoke<Args_Mod_query_rawMaterialCategory_getById, Result_Mod_query_rawMaterialCategory_getById>
          list: Invoke<Args_Mod_query_rawMaterialCategory_list, Result_Mod_query_rawMaterialCategory_list>
          update: Invoke<Args_Mod_query_rawMaterialCategory_update, Result_Mod_query_rawMaterialCategory_update>
        }
        serviceRequest: {
          create: Invoke<Args_Mod_query_serviceRequest_create, Result_Mod_query_serviceRequest_create>
          deleteById: Invoke<Args_Mod_query_serviceRequest_deleteById, Result_Mod_query_serviceRequest_deleteById>
          exportCsv: Invoke<Args_Mod_query_serviceRequest_exportCsv, Result_Mod_query_serviceRequest_exportCsv>
          getById: Invoke<Args_Mod_query_serviceRequest_getById, Result_Mod_query_serviceRequest_getById>
          list: Invoke<Args_Mod_query_serviceRequest_list, Result_Mod_query_serviceRequest_list>
          update: Invoke<Args_Mod_query_serviceRequest_update, Result_Mod_query_serviceRequest_update>
        }
        suplier: {
          create: Invoke<Args_Mod_query_suplier_create, Result_Mod_query_suplier_create>
          list: Invoke<Args_Mod_query_suplier_list, Result_Mod_query_suplier_list>
          read: Invoke<Args_Mod_query_suplier_read, Result_Mod_query_suplier_read>
          remove: Invoke<Args_Mod_query_suplier_remove, Result_Mod_query_suplier_remove>
          update: Invoke<Args_Mod_query_suplier_update, Result_Mod_query_suplier_update>
        }
      }
      user: {
        create: Invoke<Args_Mod_user_create, Result_Mod_user_create>
        get: Invoke<Args_Mod_user_get, Result_Mod_user_get>
        list: Invoke<Args_Mod_user_list, Result_Mod_user_list>
      }
    }
  }
}
export {}
