// AUTO-GENERATED FILE (runtime)
// Generated by IpcRouter
import type { z } from 'zod'
import type * as Mod_auth from '../main/routes/auth'
import type * as Mod_user from '../main/routes/user'
type Invoke<Args = unknown, Result = unknown> = (args?: Args) => Promise<Result>
type InferArgs<M, K extends string> = M extends { schemas: Record<string, any> }
  ? K extends keyof M['schemas']
    ? M['schemas'][K] extends { args: infer A extends z.ZodTypeAny }
      ? z.input<A>
      : unknown
    : unknown
  : M extends { schemas: infer S }
  ? K extends keyof S
    ? S[K] extends { args: infer A extends z.ZodTypeAny }
      ? z.input<A>
      : unknown
    : unknown
  : M extends { argsSchema: infer A extends z.ZodTypeAny }
  ? z.input<A>
  : unknown
type InferResult<M, K extends string> = M extends { schemas: Record<string, any> }
  ? K extends keyof M['schemas']
    ? M['schemas'][K] extends { result: infer R extends z.ZodTypeAny }
      ? z.output<R>
      : unknown
    : unknown
  : M extends { schemas: infer S }
  ? K extends keyof S
    ? S[K] extends { result: infer R extends z.ZodTypeAny }
      ? z.output<R>
      : unknown
    : unknown
  : M extends { resultSchema: infer R extends z.ZodTypeAny }
  ? z.output<R>
  : unknown
type Args_Mod_auth_getSession = InferArgs<typeof Mod_auth, 'getSession'>
type Result_Mod_auth_getSession = InferResult<typeof Mod_auth, 'getSession'>
type Args_Mod_auth_login = InferArgs<typeof Mod_auth, 'login'>
type Result_Mod_auth_login = InferResult<typeof Mod_auth, 'login'>
type Args_Mod_auth_logout = InferArgs<typeof Mod_auth, 'logout'>
type Result_Mod_auth_logout = InferResult<typeof Mod_auth, 'logout'>
type Args_Mod_auth_status = InferArgs<typeof Mod_auth, 'status'>
type Result_Mod_auth_status = InferResult<typeof Mod_auth, 'status'>
type Args_Mod_user_create = InferArgs<typeof Mod_user, 'create'>
type Result_Mod_user_create = InferResult<typeof Mod_user, 'create'>
type Args_Mod_user_get = InferArgs<typeof Mod_user, 'get'>
type Result_Mod_user_get = InferResult<typeof Mod_user, 'get'>
type Args_Mod_user_list = InferArgs<typeof Mod_user, 'list'>
type Result_Mod_user_list = InferResult<typeof Mod_user, 'list'>
declare global {
  interface Window {
    api: {
      auth: {
        getSession: Invoke<Args_Mod_auth_getSession, Result_Mod_auth_getSession>
        login: Invoke<Args_Mod_auth_login, Result_Mod_auth_login>
        logout: Invoke<Args_Mod_auth_logout, Result_Mod_auth_logout>
        status: Invoke<Args_Mod_auth_status, Result_Mod_auth_status>
      }
      user: {
        create: Invoke<Args_Mod_user_create, Result_Mod_user_create>
        get: Invoke<Args_Mod_user_get, Result_Mod_user_get>
        list: Invoke<Args_Mod_user_list, Result_Mod_user_list>
      }
    }
  }
}
export {}
